=== tedgjenks/School/APCompSciTesting/testing/high-scores.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT projects (project*)>
<!ELEMENT project (name, students)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT students (student*)>
<!ELEMENT student (last-name, first-name, high-score, date-time)>
<!ELEMENT last-name (#PCDATA)>
<!ELEMENT first-name (#PCDATA)>
<!ELEMENT high-score (#PCDATA)>
<!ELEMENT date-time (#PCDATA)>

=== tedgjenks/School/APCompSciTesting/testing/high-scores.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE projects SYSTEM "high-scores.dtd">
<projects>
  <project>
    <name>Coins</name>
    <students>
      <student>
        <last-name>Craig</last-name>
        <first-name>Cameron</first-name>
        <high-score>100</high-score>
        <date-time>2020-11-06T11:01:06.0302562</date-time>
      </student>
      <student>
        <last-name>Sweezy</last-name>
        <first-name>Kenneth</first-name>
        <high-score>84</high-score>
        <date-time>2020-11-06T11:01:06.0871045</date-time>
      </student>
      <student>
        <last-name>Villareal</last-name>
        <first-name>Raja</first-name>
        <high-score>100</high-score>
        <date-time>2020-11-06T14:06:46.2906963</date-time>
      </student>
    </students>
  </project>
  <project>
    <name>Hashtable</name>
    <students>
      <student>
        <last-name>Craig</last-name>
        <first-name>Cameron</first-name>
        <high-score>59</high-score>
        <date-time>2020-12-08T11:28:27.3027132</date-time>
      </student>
      <student>
        <last-name>Sweezy</last-name>
        <first-name>Kenneth</first-name>
        <high-score>100</high-score>
        <date-time>2020-12-07T10:59:32.4179063</date-time>
      </student>
      <student>
        <last-name>Villareal</last-name>
        <first-name>Raja</first-name>
        <high-score>100</high-score>
        <date-time>2020-12-03T11:13:49.0917567</date-time>
      </student>
    </students>
  </project>
  <project>
    <name>LinkedList</name>
    <students>
      <student>
        <last-name>Craig</last-name>
        <first-name>Cameron</first-name>
        <high-score>54</high-score>
        <date-time>2020-10-08T15:04:58.0810047</date-time>
      </student>
      <student>
        <last-name>Sweezy</last-name>
        <first-name>Kenneth</first-name>
        <high-score>84</high-score>
        <date-time>2020-10-13T11:27:40.8298967</date-time>
      </student>
      <student>
        <last-name>Villareal</last-name>
        <first-name>Raja</first-name>
        <high-score>100</high-score>
        <date-time>2020-10-08T10:29:36.5114174</date-time>
      </student>
    </students>
  </project>
  <project>
    <name>PhoneNumber</name>
    <students>
      <student>
        <last-name>Craig</last-name>
        <first-name>Cameron</first-name>
        <high-score>65</high-score>
        <date-time>2020-11-10T10:14:13.2034178</date-time>
      </student>
      <student>
        <last-name>Sweezy</last-name>
        <first-name>Kenneth</first-name>
        <high-score>96</high-score>
        <date-time>2020-11-10T11:27:41.9843504</date-time>
      </student>
      <student>
        <last-name>Villareal</last-name>
        <first-name>Raja</first-name>
        <high-score>100</high-score>
        <date-time>2020-11-09T11:12:00.6342395</date-time>
      </student>
    </students>
  </project>
  <project>
    <name>Xor</name>
    <students>
      <student>
        <last-name>Craig</last-name>
        <first-name>Cameron</first-name>
        <high-score>100</high-score>
        <date-time>2020-11-10T10:31:35.4096032</date-time>
      </student>
      <student>
        <last-name>Sweezy</last-name>
        <first-name>Kenneth</first-name>
        <high-score>100</high-score>
        <date-time>2020-10-27T10:47:46.6125176</date-time>
      </student>
      <student>
        <last-name>Villareal</last-name>
        <first-name>Raja</first-name>
        <high-score>100</high-score>
        <date-time>2020-10-13T11:34:08.4329717</date-time>
      </student>
    </students>
  </project>
</projects>
