=== tedgjenks/School/WebScraper/resources/khan-academy-rules.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT parsing-rules (relative-paths, dates?, headers, rules)>
<!ELEMENT relative-paths EMPTY>
<!ATTLIST relative-paths ka-path CDATA #REQUIRED>
<!ATTLIST relative-paths ps-path CDATA #FIXED "ka/psImport/">
<!ELEMENT dates (date?, date?)>
<!ATTLIST dates header-due-date CDATA #FIXED "Due Date">
<!ELEMENT date EMPTY>
<!ATTLIST date date-bound (begin|end) "begin">
<!ATTLIST date date-year CDATA #REQUIRED>
<!ATTLIST date date-month CDATA #REQUIRED>
<!ATTLIST date date-day CDATA #REQUIRED>
<!ELEMENT headers EMPTY>
<!ATTLIST headers assignment-name CDATA #FIXED "Assignment Name">
<!ATTLIST headers student-name CDATA #FIXED "Student Name">
<!ATTLIST headers completion-date CDATA #FIXED "Most Recent Completion Date">
<!ATTLIST headers assignment-type CDATA #FIXED "Assignment Type">
<!ELEMENT rules (rule+)>
<!ELEMENT rule (completion-rule|points-rule)>
<!ATTLIST rule assignment-type (Challenge|Project|Exercise) "Challenge">
<!ELEMENT completion-rule EMPTY>
<!ATTLIST completion-rule header-completion CDATA #FIXED "Most Recent Completion Date">
<!ATTLIST completion-rule completion-points CDATA "4">
<!ELEMENT points-rule (curve?)>
<!ATTLIST points-rule header-best-score CDATA #FIXED "Score Best Ever">
<!ATTLIST points-rule header-points-possible CDATA #FIXED "Points Possible">
<!ELEMENT curve EMPTY>
<!ATTLIST curve min-score-percent CDATA "50">
<!ATTLIST curve point-value CDATA ".5">

=== tedgjenks/School/WebScraper/resources/game_dev_ka_rules.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE parsing-rules SYSTEM "khan-academy-rules.dtd" >
<parsing-rules>
  <relative-paths ka-path="ka/ka_gd_export.csv"/>
  <dates>
  	<date date-bound="begin" date-month="5" date-day="8" date-year="2020"/>
  </dates>
  <headers/>
  <rules>
    <rule assignment-type="Challenge">
      <completion-rule completion-points="4"/>
    </rule>
    <rule assignment-type="Project">
      <completion-rule completion-points="5"/>
    </rule>
    <rule assignment-type="Exercise">
      <points-rule>
      	<curve/>
      </points-rule>
    </rule>
  </rules>
</parsing-rules>
